version: "3.8"

# ビルド用
services:
  app:
    build: &build
      context: "../build/golang"
      args: &args
        APP_VERSION: "${APP_VERSION:?required}"
        GITHUB_TOKEN: "${GITHUB_TOKEN:?required}"
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
      target: "app"
    image: "mythrnr/template-pj-golang:app-${APP_VERSION}"

  cli:
    build:
      <<: *build
      target: "cli"
    image: "mythrnr/template-pj-golang:cli-${APP_VERSION}"

  web:
    build:
      context: "../build/nginx"
      dockerfile: "Dockerfile"
      args: *args
    image: "mythrnr/template-pj-golang:web-${APP_VERSION}"
