version: "3.8"

services:
  cli:
    entrypoint: "go run cmd/cli/cli/main.go"

  database:
    ports:
      - "3306:3306"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    ports:
      - "443:443"

  docs:
    image: "nginx:alpine"
    depends_on:
      - "godoc"
    ports:
      - "80:80"
    user: "root"
    volumes:
      - "../build/nginx/godoc.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../docs/unit_tests:/var/www/html/unit_tests/github.com/mythrnr/template-pj-golang:ro"

  godoc:
    build:
      context: "../build/golang"
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
      target: "base"
    image: "mythrnr/template-pj-golang:godoc"
    command: "godoc -http=:10000 -play -v"
    expose:
      - 10000
    user: "golang"
    volumes:
      - "../.netrc:/home/golang/.netrc:ro"
      - "../:/go/src/github.com/mythrnr/template-pj-golang/:cached"
      - "template_pj_golang_go_pkg:/go/pkg:rw"
    working_dir: "/go/src/github.com/mythrnr/template-pj-golang"
