version: "3.8"

services:
  cli:
    entrypoint: "go run cmd/cli/cli/main.go"

  database:
    ports:
      - "3306:3306"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    ports:
      - "443:443"

  docs:
    image: "nginx:alpine"
    depends_on:
      - "godoc"
    ports:
      - "80:80"
    user: "root"
    volumes:
      - type: "bind"
        source: "../build/nginx/godoc.conf"
        target: "/etc/nginx/conf.d/default.conf"
        read_only: true
      - type: "bind"
        source: "../docs/unit_tests"
        target: "/var/www/html/unit_tests/github.com/mythrnr/template-pj-golang"
        read_only: true

  godoc:
    build:
      context: "../build/golang"
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
      target: "base"
    image: "mythrnr/template-pj-golang:godoc"
    command: "godoc -http=:10000 -play -v"
    expose:
      - 10000
    user: "golang"
    volumes:
      - type: "bind"
        source: "../.netrc"
        target: "/home/golang/.netrc"
        read_only: true
      - type: "bind"
        source: ".."
        target: "/go/src/github.com/mythrnr/template-pj-golang"
        read_only: true
      - type: "volume"
        source: "go_pkg"
        target: "/go/pkg"
        read_only: true
    working_dir: "/go/src/github.com/mythrnr/template-pj-golang"
