version: "3.8"

# Github Actions用
services:
  app:
    user: "root"
    volumes:
      - type: "bind"
        source: "../.netrc"
        target: "/root/.netrc"
        read_only: true

  cli:
    user: "root"

  database:
    user: "root"

  elasticsearch:
    user: "root"
