openapi: 3.0.0
info:
  title: Example APIs
  version: '1.0'
servers:
  - url: 'https://localhost'
    description: local
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: string
                example: ok
              examples:
                example:
                  value: ok
      operationId: get-ping
      description: ''
