# see: https://golangci-lint.run/usage/configuration/
run:
  go: "1.23"
  timeout: "1m"

output:
  sort-results: true

linters-settings:
  cyclop:
    max-complexity: 20
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  godox:
    keywords:
      - "TODO"
      - "FIXME"
  lll:
    line-length: 100
    tab-width: 4
  makezero:
    always: true
  misspell:
    locale: "US"
    ignore-words:
      - "some_word"
  mnd:
    ignored-functions:
      - "strconv.FormatInt"
      - "strconv.ParseFloat"
      - "strconv.ParseInt"
      - "strconv.ParseUint"
  nestif:
    min-complexity: 4
  testpackage:
    skip-regexp: "_inner_test.go"

linters:
  disable:
    - "depguard"
    - "exhaustruct"
    - "gochecknoglobals"
    - "varnamelen"
    - "wrapcheck"
    - "tagliatelle"
    # ---- deprecated ---- #
    - "exportloopref"
    # -------------------- #
  enable-all: true
  fast: false

issues:
  exclude-dirs:
    - ".devcontainer"
    - ".github"
    - ".vscode"
    - "bin"
    - "docker"
    - "docs"
    - "mocks"
    - "scripts"
