# see: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  timeout: "1m"
  skip-dirs:
    - ".devcontainer"
    - ".github"
    - ".vscode"
    - "bin"
    - "docker"
    - "docs"
    - "mocks"
    - "scripts"

output:
  sort-results: true

linters-settings:
  cyclop:
    max-complexity: 20
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  godox:
    keywords:
      - "TODO"
      - "FIXME"
  gomnd:
    settings:
      mnd:
        ignored-functions: "strconv.FormatInt,strconv.ParseFloat,strconv.ParseInt,strconv.ParseUint"
  ifshort:
    max-decl-lines: 1
    max-decl-chars: 60
  lll:
    line-length: 80
    tab-width: 4
  makezero:
    always: true
  misspell:
    locale: "US"
    ignore-words:
      - "someword"
  nestif:
    min-complexity: 4
  staticcheck:
    go: "1.17"
  testpackage:
    skip-regexp: "_inner_test.go"

linters:
  disable:
    - "gochecknoglobals"
    - "tagliatelle"
    # ---- deprecated ---- #
    - "golint"
    - "interfacer"
    - "maligned"
    - "scopelint"
    # -------------------- #
  presets:
    - "bugs"
    - "complexity"
    - "format"
    - "performance"
    - "style"
    - "unused"
  fast: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: "_test.go"
      linters:
        - "dupl"
        - "errcheck"
        - "funlen"
    - path: "config"
      linters:
        - "funlen"
