# ローカル環境用
services:
  database:
    ports:
      - "127.0.0.1:3306:3306"

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  web:
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - type: "bind"
        source: "../docs/openapi"
        target: "/var/www/docs/openapi"
        read_only: true
