# Github Actions用
x-service: &service
  user: "root"

services:
  app:
    <<: *service
    volumes:
      - type: "bind"
        source: "../.netrc"
        target: "/root/.netrc"
        read_only: true
      - type: "bind"
        source: "${GO_PKGDIR?:required}"
        target: "/go/pkg"
        read_only: false

  database: *service
