#===============================================================================
#
# アプリケーション設定ファイル
#
#   Description:
#     環境に関係なく共通な設定もしくは環境設定のデフォルト値を記載.
#     共通だとしても秘匿性のある情報は記載せず, 環境変数を設定する.
#
#   Example:
#     # env: KEY ... 環境変数名. 無い場合は '-'
#     # type: bool, int, uint, string, ... 設定値の型（Golang 準拠）
#     # required: true|false ... 環境変数が必須かどうか. env がない場合は '-'
#     # description: 1 < value < 10 など ... 設定値に関する説明
#     key: value
#
#===============================================================================

#
# アプリケーション全体に関する設定
#
app:
  # env: APP_ENV
  # type: string
  # required: false
  # description:
  #   実行環境（local|development|testing|production）
  env: "production"

  # env: APP_LISTEN_PORT
  # type: uint16
  # required: false
  # description:
  #   リッスンポート. 0〜1023 は使用不可
  listen_port: 8000

  # env: APP_LOG_LEVEL
  # type: string
  # required: false
  # description: ログレベル（debug|info|warning|error|fatal|panic）
  log_level: "warning"

#
# Cache に関する設定
#
cache:
  #
  # Redis に関する設定
  #
  redis:
    # env: CACHE_REDIS_HOST
    # type: string
    # required: true
    # description: Redis のホスト名. 環境変数から取得する
    host: ""

    # env: CACHE_REDIS_PASSWORD
    # type: string
    # required: true
    # description: パスワード. 環境変数から取得する
    password: ""

    # env: CACHE_REDIS_PORT
    # type: uint16
    # required: false
    # description: ポート番号
    port: 6379

#
# DB に関する設定
#
database:
  #
  # Connection
  #
  # Go 言語でのデータベース接続に関する設定.
  # see: http://dsas.blog.klab.org/archives/2018-02/configure-sql-db.html
  # see: https://tutuz-tech.hatenablog.com/entry/2020/03/24/170159
  connection:
    # env: DATABASE_CONN_LIFETIME
    # type: uint
    # required: true
    # description: アイドル状態の接続を何秒間保持するか.
    life_time: 0

    # env: DATABASE_CONN_MAXIDLE
    # type: uint
    # required: true
    # description:
    #   アイドル状態の接続を最大でいくつ保持するか.
    #   max_open よりも小さい値を設定する.
    max_idle: 0

    # env: DATABASE_CONN_MAXOPEN
    # type: uint
    # required: true
    # description: アイドル状態の接続を最大でいくつ保持するか.
    max_open: 0

  # env: DATABASE_LOGGING
  # type: bool
  # required: false
  # description: 実行された SQL をログ出力するかどうか
  logging: false

  #
  # MySQL
  #
  mysql:
    # env: -
    # type: string
    # required: true
    # description: DB 接続時に使用する文字コード
    charset: "utf8mb4"

    # env: DATABASE_MYSQL_DBNAME
    # type: string
    # required: true
    # description: DB 名
    database: ""

    # env: DATABASE_MYSQL_HOST_READ
    # type: string
    # required: true
    # description: レプリカのホスト名
    host_read: ""

    # env: DATABASE_MYSQL_HOST_WRITE
    # type: string
    # required: true
    # description: マスターのホスト名
    host_write: ""

    # env: DATABASE_MYSQL_PASSWORD
    # type: string
    # required: true
    # description: パスワード
    password: ""

    # env: DATABASE_MYSQL_PORT
    # type: uint16
    # required: true
    # description: ポート.
    port: 3306

    # env: -
    # type: string
    # required: true
    # description:
    #   MySQL で扱う値のタイムゾーン設定
    #   時刻は全て世界標準時で扱う
    timezone: "UTC"

    # env: DATABASE_MYSQL_USER
    # type: string
    # required: true
    # description: ユーザー名
    username: ""

#
# 外部 HTTP 接続に関する設定
#
http:
  # env: -
  # type: uint8
  # required: -
  # description:
  #   タイムアウトまでの値（秒）.
  #   Go の HTTPClient はデフォルトのタイムアウトが無いので必須
  default_timeout_seconds: 10

  # env: HTTP_PROXY
  # type: string
  # required: false
  # description: 外部接続する際に必要なProxyサーバー設定
  proxy: ""

#
# 言語に関する設定
#
lang:
  # env: -
  # type: string
  # required: -
  # description: デフォルト言語設定（ja|en-US）
  fallback: "en-US"

  # env: -
  # type: string
  # required: -
  # description: HTTP 通信のレスポンスで言語指定をする場合に指定する HTTP ヘッダ名
  http_header_name: "Accept-Language"
