#===============================================================================
#
# アプリケーション設定ファイル
#
#   Description:
#     環境に関係なく共通な設定もしくは環境設定のデフォルト値を記載
#     共通だとしても秘匿性のある情報は記載せず, .env.* ファイルに記載
#
#   Example:
#     # env: KEY ... .env ファイルでのキー名. ない場合は '-'
#     # type: bool, int, uint, string, ... 設定値の型(Golang準拠)
#     # required: true|false ... 必須かどうか.  true の値は読み込み時に空チェックをしている
#     # description: 1 < value < 10 など ... 設定値に関する説明
#     key: value
#
#===============================================================================

#
# アプリケーション全体に関する設定
#
app:
  # env: APP_ENV
  # type: string
  # required: false
  # description:
  #   実行環境（local|development|testing|production）
  env: "production"

  # env: APP_LISTEN_PORT
  # type: uint16
  # required: false
  # description:
  #   リッスンポート. 0〜1023は使用不可
  listen_port: 8000

  # env: APP_LOG_LEVEL
  # type: string
  # required: true
  # description: ログレベル（debug|info|warning|error|fatal|panic）
  log_level: "warning"

#
# DBに関する設定
#
database:
  # env: DATABASES_LOGGING
  # type: bool
  # required: false
  # description: 実行されたSQLをログ出力するかどうか
  logging: false

  #
  # MySQL
  #
  mysql:
    # env: -
    # type: string
    # required: false
    # description: DB接続時に使用する文字コード
    charset: "utf8mb4"

    # env: DATABASE_MYSQL_DBNAME
    # type: string
    # required: false
    # description: DB名
    database: ""

    # env: DATABASE_MYSQL_HOST
    # type: string
    # required: false
    # description: ホスト名
    host: ""

    # env: DATABASE_MYSQL_PASSWORD
    # type: string
    # required: false
    # description: パスワード
    password: ""

    # env: DATABASE_MYSQL_PORT
    # type: uint16
    # required: false
    # description: ポート. 0〜1023は使用不可
    port: 3306

    # env: -
    # type: string
    # required: false
    # description:
    #   MySQLで扱う値のタイムゾーン設定.
    #   時刻は全て世界標準時で扱う
    timezone: "UTC"

    # env: DATABASE_MYSQL_USER
    # type: string
    # required: false
    # description: ユーザー名
    username: ""

#
# Elasticsearchに関する設定
#
elasticsearch:
  # env: ELASTICSEARCH_HOSTS
  # type: []string
  # required: true
  # description:
  #   ホスト名の配列.
  #   環境変数で複数指定する場合はカンマ "," 区切り.
  #   環境変数で指定した場合, config.yml で指定した値は無視される
  hosts:

#
# 外部HTTP接続に関する設定
#
http:
  # env: -
  # type: uint8
  # required: true
  # description:
  #   タイムアウトまでの値（秒）.
  #   GoのHTTPClientはデフォルトのタイムアウトが無いので必須
  default_timeout: 10

  # env: HTTP_PROXY
  # type: string
  # required: false
  # description: 外部接続する際に必要なProxyサーバー設定
  proxy: ""

#
# 言語に関する設定
#
lang:
  # env: -
  # type: string
  # required: true
  # description: デフォルト言語設定（ja|en）
  fallback: "en"
