// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CLI is an autogenerated mock type for the CLI type
type CLI struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CLI) Execute(_a0 []string) {
	_m.Called(_a0)
}
