name: "Check codes"

on:
  pull_request:
  push:
    branches:
      - "nothing"
      # - "master"
      # - "develop"
    paths:
      - "!**.md"
      - "**.go"
      - "**.yml"
  workflow_dispatch:

env:
  SLACK_COLOR_FAILED: "#a92d2e"
  SLACK_COLOR: "#32bd77"
  SLACK_ICON: "https://github.com/github.png"
  SLACK_USERNAME: "GitHub Actions"

jobs:
  golangci:
    name: "golangci-lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Put .netrc"
        uses: "./.github/actions/put-netrc"
        with:
          secret-token: "${{ secrets.SECRET_TOKEN }}"

      - uses: "golangci/golangci-lint-action@v2"
        with:
          version: "latest"

  scan_vulnerabilities:
    name: "Scan Vulnerabilities"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Put .netrc"
        uses: "./.github/actions/put-netrc"
        with:
          secret-token: "${{ secrets.SECRET_TOKEN }}"

      - uses: "actions/setup-go@v1"
        with:
          go-version: "1.16"

      - name: "Write go.list file"
        run: "go list -json -m all > go.list"

      - uses: "sonatype-nexus-community/nancy-github-action@main"

  testing:
    name: "Unit Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Configure sysctl limits for Elasticsearch"
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: "actions/checkout@v2"

      - name: "Put .netrc"
        uses: "./.github/actions/put-netrc"
        with:
          location: ".netrc"
          secret-token: "${{ secrets.SECRET_TOKEN }}"

      - uses: "actions/setup-go@v1"
        with:
          go-version: "1.16"

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Get GOMODCACHE directory path"
        run: |
          GOMODCACHE=$(go env GOPATH)/pkg
          mkdir -p $GOMODCACHE

          echo "GO_PKGDIR=$GOMODCACHE" >> $GITHUB_ENV

      - name: "Cache GOMODCACHE directory"
        uses: "actions/cache@v2"
        # use this to check for `cache-hit`
        # `steps.gomodcache.outputs.cache-hit != 'true'`
        id: "gomodcache"
        with:
          path: "${{ env.GO_PKGDIR }}"
          key: "${{ runner.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/.github/workflows/check_code.yml')) }}-${{ hashFiles(format('{0}{1}', github.workspace, '/go.sum')) }}"
          restore-keys: "${{ runner.os }}-"

      - name: "Prepare Unit Test"
        run: |
          make pull \
            overridefile=github \
            go_pkgdir=${{ env.GO_PKGDIR }}

          make build-container \
            overridefile=github \
            go_pkgdir=${{ env.GO_PKGDIR }}

          make tidy \
            overridefile=github \
            go_pkgdir=${{ env.GO_PKGDIR }}

          CUR_USER=`id -u $USER`
          CUR_GROUP=`id -g $USER`
          sudo chown -R $CUR_USER:$CUR_GROUP ${{ env.GO_PKGDIR }}

      - name: "Run tests"
        run: |
          make test-json \
            overridefile=github \
            go_pkgdir=${{ env.GO_PKGDIR }} \
            1> result.json

      - name: "Annotate tests"
        if: "always()"
        uses: "guyarb/golang-test-annotations@v0.3.0"
        with:
          test-results: "result.json"

  notify:
    name: "Slack Notification on success"
    runs-on: "ubuntu-latest"
    needs:
      - "golangci"
      - "scan_vulnerabilities"
      - "testing"
    env:
      SLACK_WEBHOOK: |
        ${{ secrets[fromJSON('[
          "TESTING_SLACK_WEBHOOK",
          "PRODUCTION_SLACK_WEBHOOK"
        ]')[contains(github.ref, 'master')]] }}

    steps:
      - uses: "8398a7/action-slack@v3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK_URL: "${{ env.SLACK_WEBHOOK }}"
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              channel: '${{ secrets.SLACK_CHANNEL }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is successful.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }

  notify_failure:
    if: "failure()"
    name: "Slack Notification on failure"
    runs-on: "ubuntu-latest"
    needs:
      - "golangci"
      - "scan_vulnerabilities"
      - "testing"
      - "notify"
    env:
      SLACK_WEBHOOK: |
        ${{ secrets[fromJSON('[
          "TESTING_SLACK_WEBHOOK",
          "PRODUCTION_SLACK_WEBHOOK"
        ]')[contains(github.ref, 'master')]] }}

    steps:
      - uses: "8398a7/action-slack@v3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK_URL: "${{ env.SLACK_WEBHOOK }}"
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              channel: '${{ secrets.SLACK_CHANNEL }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is failure.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR_FAILED }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }
