name: "Deploy Application"

on:
  workflow_dispatch:
    inputs:
      env:
        type: "choice"
        default: "testing"
        description: "Release env ( `testing` or `production` )"
        options:
          - "testing"
          - "production"
        required: true
      version:
        description: "Version to deploy"
        required: true
        default: ""

permissions:
  contents: "read"

env:
  SLACK_COLOR_FAILED: "#a92d2e"
  SLACK_COLOR: "#32bd77"
  SLACK_ICON: "https://github.com/github.png"
  SLACK_USERNAME: "GitHub Actions"
  SLACK_WEBHOOK_URL: ${{ secrets[fromJSON('["TESTING_SLACK_WEBHOOK", "PRODUCTION_SLACK_WEBHOOK"]')[github.event.inputs.env == 'production']] }}

jobs:
  deploy:
    name: "Deploy Application"
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - run: echo "run commands to deploy"

  notify:
    name: "Slack Notification on success"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    needs:
      - "deploy"
    steps:
      - uses: "8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e" # v3.19.0
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              channel: '${{ secrets.SLACK_CHANNEL }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is successful.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }

  notify-failure:
    if: "${{ failure() }}"
    name: "Slack Notification on failure"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    needs:
      - "deploy"
      - "notify"
    steps:
      - uses: "8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e" # v3.19.0
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              channel: '${{ secrets.SLACK_CHANNEL }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is failure.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR_FAILED }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }
