name: "Create Release"

on:
  push:
    tags:
      - "v*"

env:
  SLACK_COLOR_FAILED: "#a92d2e"
  SLACK_COLOR: "#32bd77"
  SLACK_ICON: "https://github.com/github.png"
  SLACK_USERNAME: "GitHub Actions"

jobs:
  env:
    name: "set env"
    runs-on: "ubuntu-latest"
    outputs:
      APP_VERSION: "${{ steps.setenv.outputs.APP_VERSION }}"
      RELEASE_BRANCH: "${{ steps.setenv.outputs.RELEASE_BRANCH }}"
      RELEASE_ENV: "${{ steps.setenv.outputs.RELEASE_ENV }}"
    steps:
      - name: "Set Version"
        run: echo "APP_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - if: "contains(github.ref, '-dev')"
        name: "Set Release env variables for Testing"
        run: |
          echo "RELEASE_BRANCH=develop" >> $GITHUB_ENV
          echo "RELEASE_ENV=testing" >> $GITHUB_ENV

      - if: "!contains(github.ref, '-dev')"
        name: "Set Release env variables for Production"
        run: |
          echo "RELEASE_BRANCH=master" >> $GITHUB_ENV
          echo "RELEASE_ENV=production" >> $GITHUB_ENV

      - id: "setenv"
        run: |
          echo "::set-output name=APP_VERSION::${{ env.APP_VERSION }}"
          echo "::set-output name=RELEASE_BRANCH::${{ env.RELEASE_BRANCH }}"
          echo "::set-output name=RELEASE_ENV::${{ env.RELEASE_ENV }}"

  create_release:
    runs-on: "ubuntu-latest"
    needs:
      - "env"
    env:
      APP_VERSION: "${{ needs.env.outputs.APP_VERSION }}"
      RELEASE_BRANCH: "${{ needs.env.outputs.RELEASE_BRANCH }}"
      RELEASE_ENV: "${{ needs.env.outputs.RELEASE_ENV }}"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Login Dockerhub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build Container"
        env:
          APP_VERSION: "${{ env.APP_VERSION }}"
          GITHUB_TOKEN: "${{ secrets.SECRET_TOKEN }}"
        run: "make build"

      - name: "Push Container"
        env:
          APP_VERSION: "${{ env.APP_VERSION }}"
          GITHUB_TOKEN: "${{ secrets.SECRET_TOKEN }}"
        run: "make push"

      - name: "Create release note"
        run: |
          echo "## Change Log" >> note.txt
          echo "" >> note.txt

          git fetch origin --tags

          RECENT_TAG=$(git tag \
            --no-contains=$GITHUB_SHA \
            --sort="version:refname" \
            | tail -1)

          git log $RECENT_TAG..${{ env.APP_VERSION }} \
            --pretty=format:"- %h : %s (by @%an)" >> note.txt

      - name: "Create release"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          gh release create ${{ env.APP_VERSION }} \
            --title "Release ${{ env.APP_VERSION }}" \
            --notes-file note.txt

  notify:
    name: "Slack Notification on success"
    runs-on: "ubuntu-latest"
    needs:
      - "env"
      - "create_release"
    env:
      APP_VERSION: "${{ needs.env.outputs.APP_VERSION }}"
      RELEASE_BRANCH: "${{ needs.env.outputs.RELEASE_BRANCH }}"
      RELEASE_ENV: "${{ needs.env.outputs.RELEASE_ENV }}"
      SLACK_WEBHOOK: |
        ${{ secrets[fromJSON('[
          "PRODUCTION_SLACK_WEBHOOK",
          "TESTING_SLACK_WEBHOOK"
        ]')[contains(github.ref, '-dev')]] }}

    steps:
      - name: "Get workflow ID to deploy"
        id: "get-workflow-id-deploy"
        run: |
          result=$(curl -sL https://${{ secrets.SECRET_TOKEN }}@api.github.com/repos/${{ github.repository }}/actions/workflows)
          echo $result
          ID=$(echo $result | jq '.workflows[] | select(.path | contains("deploy_app")) | .id')

          echo "::set-output name=WORKFLOW_ID::$ID"

      - name: "Notify"
        uses: "8398a7/action-slack@v3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK_URL: "${{ env.SLACK_WEBHOOK }}"
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is successful.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }, {
                  title: 'Release URL',
                  value: 'https://github.com/${{ github.repository }}/releases/tag/${{ env.APP_VERSION }}',
                  short: false
                }, {
                  title: 'Deploy Command',
                  value: '```' + `curl -vvv -XPOST -H "Authorization: token YOUR-TOKEN" \\
                    -H "Accept: application/vnd.github.everest-preview+json" \\
                    "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get-workflow-id-deploy.outputs.WORKFLOW_ID }}/dispatches" \\
                    -d '{ "ref": "${{ env.RELEASE_BRANCH }}", "inputs": { "env": "${{ env.RELEASE_ENV }}", "version": "${{ env.APP_VERSION }}" } }'` + '```',
                  short: false
                }]
              }]
            }

  notify_failure:
    if: "failure()"
    name: "Slack Notification on failure"
    runs-on: "ubuntu-latest"
    needs:
      - "env"
      - "create_release"
      - "notify"
    env:
      SLACK_WEBHOOK: |
        ${{ secrets[fromJSON('[
          "PRODUCTION_SLACK_WEBHOOK",
          "TESTING_SLACK_WEBHOOK"
        ]')[contains(github.ref, '-dev')]] }}

    steps:
      - uses: "8398a7/action-slack@v3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK_URL: "${{ env.SLACK_WEBHOOK }}"
        with:
          status: "custom"
          custom_payload: |
            {
              username: '${{ env.SLACK_USERNAME }}',
              "icon_url": '${{ env.SLACK_ICON }}',
              text: 'Workflow [${{ github.workflow }}] is failure.',
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "http://github.com/${{ github.actor }}",
                "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
                color: '${{ env.SLACK_COLOR_FAILED }}',
                fields: [{
                  title: 'Ref',
                  value: '${{ github.ref }}',
                  short: true
                }, {
                  title: 'Event',
                  value: '${{ github.event_name }}',
                  short: true
                }, {
                  title: 'Actions URL',
                  value: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  short: false
                }]
              }]
            }
